# Base configuration

theme: Modernist
title: Esteban J. Chaves - Seismologist
description: Personal Website
email: esteban.j.chaves@una.cr

highlighter: rouge
permalink: pretty

author:
  name:           'Esteban J. Chaves'
  url:            https://twitter.com/SeisCROv
